import { create } from '@storybook/theming/create';

export default create({
  base: 'dark',
  brandTitle: 'React | TS | Vite Starter',
  brandImage: '/logo.png',
  brandTarget: '_self',
  colorPrimary: '#fac84b',
  colorSecondary: '#9673fa',
  // appBg: '#ffffff',
  // appContentBg: '#ffffff',
  // appPreviewBg: '#ffffff',
  // appBorderColor: '#6c757d',
  // appBorderRadius: 5,
  // textColor: '#000000',
  // textInverseColor: '#ffffff',
  // barTextColor: '#6c757d',
  // barSelectedColor: '#6c757d',
  // barHoverColor: '#6c757d',
  // barBg: '#ffffff',
  // inputBg: '#ffffff',
  // inputBorder: '#000000',
  // inputTextColor: '#000000',
  // inputBorderRadius: 2,
});
